// Code generated by "enumer -type=InputRelativeCode"; DO NOT EDIT.

package evdev

import (
	"fmt"
	"strings"
)

const (
	_InputRelativeCodeName_0      = "REL_XREL_YREL_ZREL_RXREL_RYREL_RZREL_HWHEELREL_DIALREL_WHEELREL_MISCREL_RESERVEDREL_WHEEL_HI_RESREL_HWHEEL_HI_RES"
	_InputRelativeCodeLowerName_0 = "rel_xrel_yrel_zrel_rxrel_ryrel_rzrel_hwheelrel_dialrel_wheelrel_miscrel_reservedrel_wheel_hi_resrel_hwheel_hi_res"
	_InputRelativeCodeName_1      = "REL_MAXREL_CNT"
	_InputRelativeCodeLowerName_1 = "rel_maxrel_cnt"
)

var (
	_InputRelativeCodeIndex_0 = [...]uint8{0, 5, 10, 15, 21, 27, 33, 43, 51, 60, 68, 80, 96, 113}
	_InputRelativeCodeIndex_1 = [...]uint8{0, 7, 14}
)

func (i InputRelativeCode) String() string {
	switch {
	case 0 <= i && i <= 12:
		return _InputRelativeCodeName_0[_InputRelativeCodeIndex_0[i]:_InputRelativeCodeIndex_0[i+1]]
	case 15 <= i && i <= 16:
		i -= 15
		return _InputRelativeCodeName_1[_InputRelativeCodeIndex_1[i]:_InputRelativeCodeIndex_1[i+1]]
	default:
		return fmt.Sprintf("InputRelativeCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _InputRelativeCodeNoOp() {
	var x [1]struct{}
	_ = x[REL_X-(0)]
	_ = x[REL_Y-(1)]
	_ = x[REL_Z-(2)]
	_ = x[REL_RX-(3)]
	_ = x[REL_RY-(4)]
	_ = x[REL_RZ-(5)]
	_ = x[REL_HWHEEL-(6)]
	_ = x[REL_DIAL-(7)]
	_ = x[REL_WHEEL-(8)]
	_ = x[REL_MISC-(9)]
	_ = x[REL_RESERVED-(10)]
	_ = x[REL_WHEEL_HI_RES-(11)]
	_ = x[REL_HWHEEL_HI_RES-(12)]
	_ = x[REL_MAX-(15)]
	_ = x[REL_CNT-(16)]
}

var _InputRelativeCodeValues = []InputRelativeCode{REL_X, REL_Y, REL_Z, REL_RX, REL_RY, REL_RZ, REL_HWHEEL, REL_DIAL, REL_WHEEL, REL_MISC, REL_RESERVED, REL_WHEEL_HI_RES, REL_HWHEEL_HI_RES, REL_MAX, REL_CNT}

var _InputRelativeCodeNameToValueMap = map[string]InputRelativeCode{
	_InputRelativeCodeName_0[0:5]:         REL_X,
	_InputRelativeCodeLowerName_0[0:5]:    REL_X,
	_InputRelativeCodeName_0[5:10]:        REL_Y,
	_InputRelativeCodeLowerName_0[5:10]:   REL_Y,
	_InputRelativeCodeName_0[10:15]:       REL_Z,
	_InputRelativeCodeLowerName_0[10:15]:  REL_Z,
	_InputRelativeCodeName_0[15:21]:       REL_RX,
	_InputRelativeCodeLowerName_0[15:21]:  REL_RX,
	_InputRelativeCodeName_0[21:27]:       REL_RY,
	_InputRelativeCodeLowerName_0[21:27]:  REL_RY,
	_InputRelativeCodeName_0[27:33]:       REL_RZ,
	_InputRelativeCodeLowerName_0[27:33]:  REL_RZ,
	_InputRelativeCodeName_0[33:43]:       REL_HWHEEL,
	_InputRelativeCodeLowerName_0[33:43]:  REL_HWHEEL,
	_InputRelativeCodeName_0[43:51]:       REL_DIAL,
	_InputRelativeCodeLowerName_0[43:51]:  REL_DIAL,
	_InputRelativeCodeName_0[51:60]:       REL_WHEEL,
	_InputRelativeCodeLowerName_0[51:60]:  REL_WHEEL,
	_InputRelativeCodeName_0[60:68]:       REL_MISC,
	_InputRelativeCodeLowerName_0[60:68]:  REL_MISC,
	_InputRelativeCodeName_0[68:80]:       REL_RESERVED,
	_InputRelativeCodeLowerName_0[68:80]:  REL_RESERVED,
	_InputRelativeCodeName_0[80:96]:       REL_WHEEL_HI_RES,
	_InputRelativeCodeLowerName_0[80:96]:  REL_WHEEL_HI_RES,
	_InputRelativeCodeName_0[96:113]:      REL_HWHEEL_HI_RES,
	_InputRelativeCodeLowerName_0[96:113]: REL_HWHEEL_HI_RES,
	_InputRelativeCodeName_1[0:7]:         REL_MAX,
	_InputRelativeCodeLowerName_1[0:7]:    REL_MAX,
	_InputRelativeCodeName_1[7:14]:        REL_CNT,
	_InputRelativeCodeLowerName_1[7:14]:   REL_CNT,
}

var _InputRelativeCodeNames = []string{
	_InputRelativeCodeName_0[0:5],
	_InputRelativeCodeName_0[5:10],
	_InputRelativeCodeName_0[10:15],
	_InputRelativeCodeName_0[15:21],
	_InputRelativeCodeName_0[21:27],
	_InputRelativeCodeName_0[27:33],
	_InputRelativeCodeName_0[33:43],
	_InputRelativeCodeName_0[43:51],
	_InputRelativeCodeName_0[51:60],
	_InputRelativeCodeName_0[60:68],
	_InputRelativeCodeName_0[68:80],
	_InputRelativeCodeName_0[80:96],
	_InputRelativeCodeName_0[96:113],
	_InputRelativeCodeName_1[0:7],
	_InputRelativeCodeName_1[7:14],
}

// InputRelativeCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func InputRelativeCodeString(s string) (InputRelativeCode, error) {
	if val, ok := _InputRelativeCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _InputRelativeCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to InputRelativeCode values", s)
}

// InputRelativeCodeValues returns all values of the enum
func InputRelativeCodeValues() []InputRelativeCode {
	return _InputRelativeCodeValues
}

// InputRelativeCodeStrings returns a slice of all String values of the enum
func InputRelativeCodeStrings() []string {
	strs := make([]string, len(_InputRelativeCodeNames))
	copy(strs, _InputRelativeCodeNames)
	return strs
}

// IsAInputRelativeCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i InputRelativeCode) IsAInputRelativeCode() bool {
	for _, v := range _InputRelativeCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
