// Code generated by "enumer -type=AbsoluteCode"; DO NOT EDIT.

package input

import (
	"fmt"
	"strings"
)

const (
	_AbsoluteCodeName_0      = "ABS_XABS_YABS_ZABS_RXABS_RYABS_RZABS_THROTTLEABS_RUDDERABS_WHEELABS_GASABS_BRAKE"
	_AbsoluteCodeLowerName_0 = "abs_xabs_yabs_zabs_rxabs_ryabs_rzabs_throttleabs_rudderabs_wheelabs_gasabs_brake"
	_AbsoluteCodeName_1      = "ABS_HAT0XABS_HAT0YABS_HAT1XABS_HAT1YABS_HAT2XABS_HAT2YABS_HAT3XABS_HAT3YABS_PRESSUREABS_DISTANCEABS_TILT_XABS_TILT_YABS_TOOL_WIDTH"
	_AbsoluteCodeLowerName_1 = "abs_hat0xabs_hat0yabs_hat1xabs_hat1yabs_hat2xabs_hat2yabs_hat3xabs_hat3yabs_pressureabs_distanceabs_tilt_xabs_tilt_yabs_tool_width"
	_AbsoluteCodeName_2      = "ABS_VOLUMEABS_PROFILE"
	_AbsoluteCodeLowerName_2 = "abs_volumeabs_profile"
	_AbsoluteCodeName_3      = "ABS_MISC"
	_AbsoluteCodeLowerName_3 = "abs_misc"
	_AbsoluteCodeName_4      = "ABS_RESERVEDABS_MT_SLOTABS_MT_TOUCH_MAJORABS_MT_TOUCH_MINORABS_MT_WIDTH_MAJORABS_MT_WIDTH_MINORABS_MT_ORIENTATIONABS_MT_POSITION_XABS_MT_POSITION_YABS_MT_TOOL_TYPEABS_MT_BLOB_IDABS_MT_TRACKING_IDABS_MT_PRESSUREABS_MT_DISTANCEABS_MT_TOOL_XABS_MT_TOOL_Y"
	_AbsoluteCodeLowerName_4 = "abs_reservedabs_mt_slotabs_mt_touch_majorabs_mt_touch_minorabs_mt_width_majorabs_mt_width_minorabs_mt_orientationabs_mt_position_xabs_mt_position_yabs_mt_tool_typeabs_mt_blob_idabs_mt_tracking_idabs_mt_pressureabs_mt_distanceabs_mt_tool_xabs_mt_tool_y"
	_AbsoluteCodeName_5      = "ABS_MAXABS_CNT"
	_AbsoluteCodeLowerName_5 = "abs_maxabs_cnt"
)

var (
	_AbsoluteCodeIndex_0 = [...]uint8{0, 5, 10, 15, 21, 27, 33, 45, 55, 64, 71, 80}
	_AbsoluteCodeIndex_1 = [...]uint8{0, 9, 18, 27, 36, 45, 54, 63, 72, 84, 96, 106, 116, 130}
	_AbsoluteCodeIndex_2 = [...]uint8{0, 10, 21}
	_AbsoluteCodeIndex_3 = [...]uint8{0, 8}
	_AbsoluteCodeIndex_4 = [...]uint8{0, 12, 23, 41, 59, 77, 95, 113, 130, 147, 163, 177, 195, 210, 225, 238, 251}
	_AbsoluteCodeIndex_5 = [...]uint8{0, 7, 14}
)

func (i AbsoluteCode) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _AbsoluteCodeName_0[_AbsoluteCodeIndex_0[i]:_AbsoluteCodeIndex_0[i+1]]
	case 16 <= i && i <= 28:
		i -= 16
		return _AbsoluteCodeName_1[_AbsoluteCodeIndex_1[i]:_AbsoluteCodeIndex_1[i+1]]
	case 32 <= i && i <= 33:
		i -= 32
		return _AbsoluteCodeName_2[_AbsoluteCodeIndex_2[i]:_AbsoluteCodeIndex_2[i+1]]
	case i == 40:
		return _AbsoluteCodeName_3
	case 46 <= i && i <= 61:
		i -= 46
		return _AbsoluteCodeName_4[_AbsoluteCodeIndex_4[i]:_AbsoluteCodeIndex_4[i+1]]
	case 63 <= i && i <= 64:
		i -= 63
		return _AbsoluteCodeName_5[_AbsoluteCodeIndex_5[i]:_AbsoluteCodeIndex_5[i+1]]
	default:
		return fmt.Sprintf("AbsoluteCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AbsoluteCodeNoOp() {
	var x [1]struct{}
	_ = x[ABS_X-(0)]
	_ = x[ABS_Y-(1)]
	_ = x[ABS_Z-(2)]
	_ = x[ABS_RX-(3)]
	_ = x[ABS_RY-(4)]
	_ = x[ABS_RZ-(5)]
	_ = x[ABS_THROTTLE-(6)]
	_ = x[ABS_RUDDER-(7)]
	_ = x[ABS_WHEEL-(8)]
	_ = x[ABS_GAS-(9)]
	_ = x[ABS_BRAKE-(10)]
	_ = x[ABS_HAT0X-(16)]
	_ = x[ABS_HAT0Y-(17)]
	_ = x[ABS_HAT1X-(18)]
	_ = x[ABS_HAT1Y-(19)]
	_ = x[ABS_HAT2X-(20)]
	_ = x[ABS_HAT2Y-(21)]
	_ = x[ABS_HAT3X-(22)]
	_ = x[ABS_HAT3Y-(23)]
	_ = x[ABS_PRESSURE-(24)]
	_ = x[ABS_DISTANCE-(25)]
	_ = x[ABS_TILT_X-(26)]
	_ = x[ABS_TILT_Y-(27)]
	_ = x[ABS_TOOL_WIDTH-(28)]
	_ = x[ABS_VOLUME-(32)]
	_ = x[ABS_PROFILE-(33)]
	_ = x[ABS_MISC-(40)]
	_ = x[ABS_RESERVED-(46)]
	_ = x[ABS_MT_SLOT-(47)]
	_ = x[ABS_MT_TOUCH_MAJOR-(48)]
	_ = x[ABS_MT_TOUCH_MINOR-(49)]
	_ = x[ABS_MT_WIDTH_MAJOR-(50)]
	_ = x[ABS_MT_WIDTH_MINOR-(51)]
	_ = x[ABS_MT_ORIENTATION-(52)]
	_ = x[ABS_MT_POSITION_X-(53)]
	_ = x[ABS_MT_POSITION_Y-(54)]
	_ = x[ABS_MT_TOOL_TYPE-(55)]
	_ = x[ABS_MT_BLOB_ID-(56)]
	_ = x[ABS_MT_TRACKING_ID-(57)]
	_ = x[ABS_MT_PRESSURE-(58)]
	_ = x[ABS_MT_DISTANCE-(59)]
	_ = x[ABS_MT_TOOL_X-(60)]
	_ = x[ABS_MT_TOOL_Y-(61)]
	_ = x[ABS_MAX-(63)]
	_ = x[ABS_CNT-(64)]
}

var _AbsoluteCodeValues = []AbsoluteCode{ABS_X, ABS_Y, ABS_Z, ABS_RX, ABS_RY, ABS_RZ, ABS_THROTTLE, ABS_RUDDER, ABS_WHEEL, ABS_GAS, ABS_BRAKE, ABS_HAT0X, ABS_HAT0Y, ABS_HAT1X, ABS_HAT1Y, ABS_HAT2X, ABS_HAT2Y, ABS_HAT3X, ABS_HAT3Y, ABS_PRESSURE, ABS_DISTANCE, ABS_TILT_X, ABS_TILT_Y, ABS_TOOL_WIDTH, ABS_VOLUME, ABS_PROFILE, ABS_MISC, ABS_RESERVED, ABS_MT_SLOT, ABS_MT_TOUCH_MAJOR, ABS_MT_TOUCH_MINOR, ABS_MT_WIDTH_MAJOR, ABS_MT_WIDTH_MINOR, ABS_MT_ORIENTATION, ABS_MT_POSITION_X, ABS_MT_POSITION_Y, ABS_MT_TOOL_TYPE, ABS_MT_BLOB_ID, ABS_MT_TRACKING_ID, ABS_MT_PRESSURE, ABS_MT_DISTANCE, ABS_MT_TOOL_X, ABS_MT_TOOL_Y, ABS_MAX, ABS_CNT}

var _AbsoluteCodeNameToValueMap = map[string]AbsoluteCode{
	_AbsoluteCodeName_0[0:5]:          ABS_X,
	_AbsoluteCodeLowerName_0[0:5]:     ABS_X,
	_AbsoluteCodeName_0[5:10]:         ABS_Y,
	_AbsoluteCodeLowerName_0[5:10]:    ABS_Y,
	_AbsoluteCodeName_0[10:15]:        ABS_Z,
	_AbsoluteCodeLowerName_0[10:15]:   ABS_Z,
	_AbsoluteCodeName_0[15:21]:        ABS_RX,
	_AbsoluteCodeLowerName_0[15:21]:   ABS_RX,
	_AbsoluteCodeName_0[21:27]:        ABS_RY,
	_AbsoluteCodeLowerName_0[21:27]:   ABS_RY,
	_AbsoluteCodeName_0[27:33]:        ABS_RZ,
	_AbsoluteCodeLowerName_0[27:33]:   ABS_RZ,
	_AbsoluteCodeName_0[33:45]:        ABS_THROTTLE,
	_AbsoluteCodeLowerName_0[33:45]:   ABS_THROTTLE,
	_AbsoluteCodeName_0[45:55]:        ABS_RUDDER,
	_AbsoluteCodeLowerName_0[45:55]:   ABS_RUDDER,
	_AbsoluteCodeName_0[55:64]:        ABS_WHEEL,
	_AbsoluteCodeLowerName_0[55:64]:   ABS_WHEEL,
	_AbsoluteCodeName_0[64:71]:        ABS_GAS,
	_AbsoluteCodeLowerName_0[64:71]:   ABS_GAS,
	_AbsoluteCodeName_0[71:80]:        ABS_BRAKE,
	_AbsoluteCodeLowerName_0[71:80]:   ABS_BRAKE,
	_AbsoluteCodeName_1[0:9]:          ABS_HAT0X,
	_AbsoluteCodeLowerName_1[0:9]:     ABS_HAT0X,
	_AbsoluteCodeName_1[9:18]:         ABS_HAT0Y,
	_AbsoluteCodeLowerName_1[9:18]:    ABS_HAT0Y,
	_AbsoluteCodeName_1[18:27]:        ABS_HAT1X,
	_AbsoluteCodeLowerName_1[18:27]:   ABS_HAT1X,
	_AbsoluteCodeName_1[27:36]:        ABS_HAT1Y,
	_AbsoluteCodeLowerName_1[27:36]:   ABS_HAT1Y,
	_AbsoluteCodeName_1[36:45]:        ABS_HAT2X,
	_AbsoluteCodeLowerName_1[36:45]:   ABS_HAT2X,
	_AbsoluteCodeName_1[45:54]:        ABS_HAT2Y,
	_AbsoluteCodeLowerName_1[45:54]:   ABS_HAT2Y,
	_AbsoluteCodeName_1[54:63]:        ABS_HAT3X,
	_AbsoluteCodeLowerName_1[54:63]:   ABS_HAT3X,
	_AbsoluteCodeName_1[63:72]:        ABS_HAT3Y,
	_AbsoluteCodeLowerName_1[63:72]:   ABS_HAT3Y,
	_AbsoluteCodeName_1[72:84]:        ABS_PRESSURE,
	_AbsoluteCodeLowerName_1[72:84]:   ABS_PRESSURE,
	_AbsoluteCodeName_1[84:96]:        ABS_DISTANCE,
	_AbsoluteCodeLowerName_1[84:96]:   ABS_DISTANCE,
	_AbsoluteCodeName_1[96:106]:       ABS_TILT_X,
	_AbsoluteCodeLowerName_1[96:106]:  ABS_TILT_X,
	_AbsoluteCodeName_1[106:116]:      ABS_TILT_Y,
	_AbsoluteCodeLowerName_1[106:116]: ABS_TILT_Y,
	_AbsoluteCodeName_1[116:130]:      ABS_TOOL_WIDTH,
	_AbsoluteCodeLowerName_1[116:130]: ABS_TOOL_WIDTH,
	_AbsoluteCodeName_2[0:10]:         ABS_VOLUME,
	_AbsoluteCodeLowerName_2[0:10]:    ABS_VOLUME,
	_AbsoluteCodeName_2[10:21]:        ABS_PROFILE,
	_AbsoluteCodeLowerName_2[10:21]:   ABS_PROFILE,
	_AbsoluteCodeName_3[0:8]:          ABS_MISC,
	_AbsoluteCodeLowerName_3[0:8]:     ABS_MISC,
	_AbsoluteCodeName_4[0:12]:         ABS_RESERVED,
	_AbsoluteCodeLowerName_4[0:12]:    ABS_RESERVED,
	_AbsoluteCodeName_4[12:23]:        ABS_MT_SLOT,
	_AbsoluteCodeLowerName_4[12:23]:   ABS_MT_SLOT,
	_AbsoluteCodeName_4[23:41]:        ABS_MT_TOUCH_MAJOR,
	_AbsoluteCodeLowerName_4[23:41]:   ABS_MT_TOUCH_MAJOR,
	_AbsoluteCodeName_4[41:59]:        ABS_MT_TOUCH_MINOR,
	_AbsoluteCodeLowerName_4[41:59]:   ABS_MT_TOUCH_MINOR,
	_AbsoluteCodeName_4[59:77]:        ABS_MT_WIDTH_MAJOR,
	_AbsoluteCodeLowerName_4[59:77]:   ABS_MT_WIDTH_MAJOR,
	_AbsoluteCodeName_4[77:95]:        ABS_MT_WIDTH_MINOR,
	_AbsoluteCodeLowerName_4[77:95]:   ABS_MT_WIDTH_MINOR,
	_AbsoluteCodeName_4[95:113]:       ABS_MT_ORIENTATION,
	_AbsoluteCodeLowerName_4[95:113]:  ABS_MT_ORIENTATION,
	_AbsoluteCodeName_4[113:130]:      ABS_MT_POSITION_X,
	_AbsoluteCodeLowerName_4[113:130]: ABS_MT_POSITION_X,
	_AbsoluteCodeName_4[130:147]:      ABS_MT_POSITION_Y,
	_AbsoluteCodeLowerName_4[130:147]: ABS_MT_POSITION_Y,
	_AbsoluteCodeName_4[147:163]:      ABS_MT_TOOL_TYPE,
	_AbsoluteCodeLowerName_4[147:163]: ABS_MT_TOOL_TYPE,
	_AbsoluteCodeName_4[163:177]:      ABS_MT_BLOB_ID,
	_AbsoluteCodeLowerName_4[163:177]: ABS_MT_BLOB_ID,
	_AbsoluteCodeName_4[177:195]:      ABS_MT_TRACKING_ID,
	_AbsoluteCodeLowerName_4[177:195]: ABS_MT_TRACKING_ID,
	_AbsoluteCodeName_4[195:210]:      ABS_MT_PRESSURE,
	_AbsoluteCodeLowerName_4[195:210]: ABS_MT_PRESSURE,
	_AbsoluteCodeName_4[210:225]:      ABS_MT_DISTANCE,
	_AbsoluteCodeLowerName_4[210:225]: ABS_MT_DISTANCE,
	_AbsoluteCodeName_4[225:238]:      ABS_MT_TOOL_X,
	_AbsoluteCodeLowerName_4[225:238]: ABS_MT_TOOL_X,
	_AbsoluteCodeName_4[238:251]:      ABS_MT_TOOL_Y,
	_AbsoluteCodeLowerName_4[238:251]: ABS_MT_TOOL_Y,
	_AbsoluteCodeName_5[0:7]:          ABS_MAX,
	_AbsoluteCodeLowerName_5[0:7]:     ABS_MAX,
	_AbsoluteCodeName_5[7:14]:         ABS_CNT,
	_AbsoluteCodeLowerName_5[7:14]:    ABS_CNT,
}

var _AbsoluteCodeNames = []string{
	_AbsoluteCodeName_0[0:5],
	_AbsoluteCodeName_0[5:10],
	_AbsoluteCodeName_0[10:15],
	_AbsoluteCodeName_0[15:21],
	_AbsoluteCodeName_0[21:27],
	_AbsoluteCodeName_0[27:33],
	_AbsoluteCodeName_0[33:45],
	_AbsoluteCodeName_0[45:55],
	_AbsoluteCodeName_0[55:64],
	_AbsoluteCodeName_0[64:71],
	_AbsoluteCodeName_0[71:80],
	_AbsoluteCodeName_1[0:9],
	_AbsoluteCodeName_1[9:18],
	_AbsoluteCodeName_1[18:27],
	_AbsoluteCodeName_1[27:36],
	_AbsoluteCodeName_1[36:45],
	_AbsoluteCodeName_1[45:54],
	_AbsoluteCodeName_1[54:63],
	_AbsoluteCodeName_1[63:72],
	_AbsoluteCodeName_1[72:84],
	_AbsoluteCodeName_1[84:96],
	_AbsoluteCodeName_1[96:106],
	_AbsoluteCodeName_1[106:116],
	_AbsoluteCodeName_1[116:130],
	_AbsoluteCodeName_2[0:10],
	_AbsoluteCodeName_2[10:21],
	_AbsoluteCodeName_3[0:8],
	_AbsoluteCodeName_4[0:12],
	_AbsoluteCodeName_4[12:23],
	_AbsoluteCodeName_4[23:41],
	_AbsoluteCodeName_4[41:59],
	_AbsoluteCodeName_4[59:77],
	_AbsoluteCodeName_4[77:95],
	_AbsoluteCodeName_4[95:113],
	_AbsoluteCodeName_4[113:130],
	_AbsoluteCodeName_4[130:147],
	_AbsoluteCodeName_4[147:163],
	_AbsoluteCodeName_4[163:177],
	_AbsoluteCodeName_4[177:195],
	_AbsoluteCodeName_4[195:210],
	_AbsoluteCodeName_4[210:225],
	_AbsoluteCodeName_4[225:238],
	_AbsoluteCodeName_4[238:251],
	_AbsoluteCodeName_5[0:7],
	_AbsoluteCodeName_5[7:14],
}

// AbsoluteCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AbsoluteCodeString(s string) (AbsoluteCode, error) {
	if val, ok := _AbsoluteCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AbsoluteCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AbsoluteCode values", s)
}

// AbsoluteCodeValues returns all values of the enum
func AbsoluteCodeValues() []AbsoluteCode {
	return _AbsoluteCodeValues
}

// AbsoluteCodeStrings returns a slice of all String values of the enum
func AbsoluteCodeStrings() []string {
	strs := make([]string, len(_AbsoluteCodeNames))
	copy(strs, _AbsoluteCodeNames)
	return strs
}

// IsAAbsoluteCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AbsoluteCode) IsAAbsoluteCode() bool {
	for _, v := range _AbsoluteCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
