// Code generated by "enumer -type=BusCode"; DO NOT EDIT.

package input

import (
	"fmt"
	"strings"
)

const (
	_BusCodeName_0      = "BUS_PCIBUS_ISAPNPBUS_USBBUS_HILBUS_BLUETOOTHBUS_VIRTUAL"
	_BusCodeLowerName_0 = "bus_pcibus_isapnpbus_usbbus_hilbus_bluetoothbus_virtual"
	_BusCodeName_1      = "BUS_ISABUS_I8042BUS_XTKBDBUS_RS232BUS_GAMEPORTBUS_PARPORTBUS_AMIGABUS_ADBBUS_I2CBUS_HOSTBUS_GSCBUS_ATARIBUS_SPIBUS_RMIBUS_CECBUS_INTEL_ISHTPBUS_AMD_SFH"
	_BusCodeLowerName_1 = "bus_isabus_i8042bus_xtkbdbus_rs232bus_gameportbus_parportbus_amigabus_adbbus_i2cbus_hostbus_gscbus_ataribus_spibus_rmibus_cecbus_intel_ishtpbus_amd_sfh"
)

var (
	_BusCodeIndex_0 = [...]uint8{0, 7, 17, 24, 31, 44, 55}
	_BusCodeIndex_1 = [...]uint8{0, 7, 16, 25, 34, 46, 57, 66, 73, 80, 88, 95, 104, 111, 118, 125, 140, 151}
)

func (i BusCode) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _BusCodeName_0[_BusCodeIndex_0[i]:_BusCodeIndex_0[i+1]]
	case 16 <= i && i <= 32:
		i -= 16
		return _BusCodeName_1[_BusCodeIndex_1[i]:_BusCodeIndex_1[i+1]]
	default:
		return fmt.Sprintf("BusCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BusCodeNoOp() {
	var x [1]struct{}
	_ = x[BUS_PCI-(1)]
	_ = x[BUS_ISAPNP-(2)]
	_ = x[BUS_USB-(3)]
	_ = x[BUS_HIL-(4)]
	_ = x[BUS_BLUETOOTH-(5)]
	_ = x[BUS_VIRTUAL-(6)]
	_ = x[BUS_ISA-(16)]
	_ = x[BUS_I8042-(17)]
	_ = x[BUS_XTKBD-(18)]
	_ = x[BUS_RS232-(19)]
	_ = x[BUS_GAMEPORT-(20)]
	_ = x[BUS_PARPORT-(21)]
	_ = x[BUS_AMIGA-(22)]
	_ = x[BUS_ADB-(23)]
	_ = x[BUS_I2C-(24)]
	_ = x[BUS_HOST-(25)]
	_ = x[BUS_GSC-(26)]
	_ = x[BUS_ATARI-(27)]
	_ = x[BUS_SPI-(28)]
	_ = x[BUS_RMI-(29)]
	_ = x[BUS_CEC-(30)]
	_ = x[BUS_INTEL_ISHTP-(31)]
	_ = x[BUS_AMD_SFH-(32)]
}

var _BusCodeValues = []BusCode{BUS_PCI, BUS_ISAPNP, BUS_USB, BUS_HIL, BUS_BLUETOOTH, BUS_VIRTUAL, BUS_ISA, BUS_I8042, BUS_XTKBD, BUS_RS232, BUS_GAMEPORT, BUS_PARPORT, BUS_AMIGA, BUS_ADB, BUS_I2C, BUS_HOST, BUS_GSC, BUS_ATARI, BUS_SPI, BUS_RMI, BUS_CEC, BUS_INTEL_ISHTP, BUS_AMD_SFH}

var _BusCodeNameToValueMap = map[string]BusCode{
	_BusCodeName_0[0:7]:          BUS_PCI,
	_BusCodeLowerName_0[0:7]:     BUS_PCI,
	_BusCodeName_0[7:17]:         BUS_ISAPNP,
	_BusCodeLowerName_0[7:17]:    BUS_ISAPNP,
	_BusCodeName_0[17:24]:        BUS_USB,
	_BusCodeLowerName_0[17:24]:   BUS_USB,
	_BusCodeName_0[24:31]:        BUS_HIL,
	_BusCodeLowerName_0[24:31]:   BUS_HIL,
	_BusCodeName_0[31:44]:        BUS_BLUETOOTH,
	_BusCodeLowerName_0[31:44]:   BUS_BLUETOOTH,
	_BusCodeName_0[44:55]:        BUS_VIRTUAL,
	_BusCodeLowerName_0[44:55]:   BUS_VIRTUAL,
	_BusCodeName_1[0:7]:          BUS_ISA,
	_BusCodeLowerName_1[0:7]:     BUS_ISA,
	_BusCodeName_1[7:16]:         BUS_I8042,
	_BusCodeLowerName_1[7:16]:    BUS_I8042,
	_BusCodeName_1[16:25]:        BUS_XTKBD,
	_BusCodeLowerName_1[16:25]:   BUS_XTKBD,
	_BusCodeName_1[25:34]:        BUS_RS232,
	_BusCodeLowerName_1[25:34]:   BUS_RS232,
	_BusCodeName_1[34:46]:        BUS_GAMEPORT,
	_BusCodeLowerName_1[34:46]:   BUS_GAMEPORT,
	_BusCodeName_1[46:57]:        BUS_PARPORT,
	_BusCodeLowerName_1[46:57]:   BUS_PARPORT,
	_BusCodeName_1[57:66]:        BUS_AMIGA,
	_BusCodeLowerName_1[57:66]:   BUS_AMIGA,
	_BusCodeName_1[66:73]:        BUS_ADB,
	_BusCodeLowerName_1[66:73]:   BUS_ADB,
	_BusCodeName_1[73:80]:        BUS_I2C,
	_BusCodeLowerName_1[73:80]:   BUS_I2C,
	_BusCodeName_1[80:88]:        BUS_HOST,
	_BusCodeLowerName_1[80:88]:   BUS_HOST,
	_BusCodeName_1[88:95]:        BUS_GSC,
	_BusCodeLowerName_1[88:95]:   BUS_GSC,
	_BusCodeName_1[95:104]:       BUS_ATARI,
	_BusCodeLowerName_1[95:104]:  BUS_ATARI,
	_BusCodeName_1[104:111]:      BUS_SPI,
	_BusCodeLowerName_1[104:111]: BUS_SPI,
	_BusCodeName_1[111:118]:      BUS_RMI,
	_BusCodeLowerName_1[111:118]: BUS_RMI,
	_BusCodeName_1[118:125]:      BUS_CEC,
	_BusCodeLowerName_1[118:125]: BUS_CEC,
	_BusCodeName_1[125:140]:      BUS_INTEL_ISHTP,
	_BusCodeLowerName_1[125:140]: BUS_INTEL_ISHTP,
	_BusCodeName_1[140:151]:      BUS_AMD_SFH,
	_BusCodeLowerName_1[140:151]: BUS_AMD_SFH,
}

var _BusCodeNames = []string{
	_BusCodeName_0[0:7],
	_BusCodeName_0[7:17],
	_BusCodeName_0[17:24],
	_BusCodeName_0[24:31],
	_BusCodeName_0[31:44],
	_BusCodeName_0[44:55],
	_BusCodeName_1[0:7],
	_BusCodeName_1[7:16],
	_BusCodeName_1[16:25],
	_BusCodeName_1[25:34],
	_BusCodeName_1[34:46],
	_BusCodeName_1[46:57],
	_BusCodeName_1[57:66],
	_BusCodeName_1[66:73],
	_BusCodeName_1[73:80],
	_BusCodeName_1[80:88],
	_BusCodeName_1[88:95],
	_BusCodeName_1[95:104],
	_BusCodeName_1[104:111],
	_BusCodeName_1[111:118],
	_BusCodeName_1[118:125],
	_BusCodeName_1[125:140],
	_BusCodeName_1[140:151],
}

// BusCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BusCodeString(s string) (BusCode, error) {
	if val, ok := _BusCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BusCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BusCode values", s)
}

// BusCodeValues returns all values of the enum
func BusCodeValues() []BusCode {
	return _BusCodeValues
}

// BusCodeStrings returns a slice of all String values of the enum
func BusCodeStrings() []string {
	strs := make([]string, len(_BusCodeNames))
	copy(strs, _BusCodeNames)
	return strs
}

// IsABusCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BusCode) IsABusCode() bool {
	for _, v := range _BusCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
