// Code generated by "enumer -type=InputMiscCode"; DO NOT EDIT.

package input

import (
	"fmt"
	"strings"
)

const (
	_InputMiscCodeName_0      = "MSC_SERIALMSC_PULSELEDMSC_GESTUREMSC_RAWMSC_SCANMSC_TIMESTAMP"
	_InputMiscCodeLowerName_0 = "msc_serialmsc_pulseledmsc_gesturemsc_rawmsc_scanmsc_timestamp"
	_InputMiscCodeName_1      = "MSC_MAXMSC_CNT"
	_InputMiscCodeLowerName_1 = "msc_maxmsc_cnt"
)

var (
	_InputMiscCodeIndex_0 = [...]uint8{0, 10, 22, 33, 40, 48, 61}
	_InputMiscCodeIndex_1 = [...]uint8{0, 7, 14}
)

func (i InputMiscCode) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _InputMiscCodeName_0[_InputMiscCodeIndex_0[i]:_InputMiscCodeIndex_0[i+1]]
	case 7 <= i && i <= 8:
		i -= 7
		return _InputMiscCodeName_1[_InputMiscCodeIndex_1[i]:_InputMiscCodeIndex_1[i+1]]
	default:
		return fmt.Sprintf("InputMiscCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _InputMiscCodeNoOp() {
	var x [1]struct{}
	_ = x[MSC_SERIAL-(0)]
	_ = x[MSC_PULSELED-(1)]
	_ = x[MSC_GESTURE-(2)]
	_ = x[MSC_RAW-(3)]
	_ = x[MSC_SCAN-(4)]
	_ = x[MSC_TIMESTAMP-(5)]
	_ = x[MSC_MAX-(7)]
	_ = x[MSC_CNT-(8)]
}

var _InputMiscCodeValues = []InputMiscCode{MSC_SERIAL, MSC_PULSELED, MSC_GESTURE, MSC_RAW, MSC_SCAN, MSC_TIMESTAMP, MSC_MAX, MSC_CNT}

var _InputMiscCodeNameToValueMap = map[string]InputMiscCode{
	_InputMiscCodeName_0[0:10]:       MSC_SERIAL,
	_InputMiscCodeLowerName_0[0:10]:  MSC_SERIAL,
	_InputMiscCodeName_0[10:22]:      MSC_PULSELED,
	_InputMiscCodeLowerName_0[10:22]: MSC_PULSELED,
	_InputMiscCodeName_0[22:33]:      MSC_GESTURE,
	_InputMiscCodeLowerName_0[22:33]: MSC_GESTURE,
	_InputMiscCodeName_0[33:40]:      MSC_RAW,
	_InputMiscCodeLowerName_0[33:40]: MSC_RAW,
	_InputMiscCodeName_0[40:48]:      MSC_SCAN,
	_InputMiscCodeLowerName_0[40:48]: MSC_SCAN,
	_InputMiscCodeName_0[48:61]:      MSC_TIMESTAMP,
	_InputMiscCodeLowerName_0[48:61]: MSC_TIMESTAMP,
	_InputMiscCodeName_1[0:7]:        MSC_MAX,
	_InputMiscCodeLowerName_1[0:7]:   MSC_MAX,
	_InputMiscCodeName_1[7:14]:       MSC_CNT,
	_InputMiscCodeLowerName_1[7:14]:  MSC_CNT,
}

var _InputMiscCodeNames = []string{
	_InputMiscCodeName_0[0:10],
	_InputMiscCodeName_0[10:22],
	_InputMiscCodeName_0[22:33],
	_InputMiscCodeName_0[33:40],
	_InputMiscCodeName_0[40:48],
	_InputMiscCodeName_0[48:61],
	_InputMiscCodeName_1[0:7],
	_InputMiscCodeName_1[7:14],
}

// InputMiscCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func InputMiscCodeString(s string) (InputMiscCode, error) {
	if val, ok := _InputMiscCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _InputMiscCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to InputMiscCode values", s)
}

// InputMiscCodeValues returns all values of the enum
func InputMiscCodeValues() []InputMiscCode {
	return _InputMiscCodeValues
}

// InputMiscCodeStrings returns a slice of all String values of the enum
func InputMiscCodeStrings() []string {
	strs := make([]string, len(_InputMiscCodeNames))
	copy(strs, _InputMiscCodeNames)
	return strs
}

// IsAInputMiscCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i InputMiscCode) IsAInputMiscCode() bool {
	for _, v := range _InputMiscCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
