// Code generated by "enumer -type=InputFFCode"; DO NOT EDIT.

package input

import (
	"fmt"
	"strings"
)

const (
	_InputFFCodeName_0      = "FF_RUMBLEFF_PERIODICFF_CONSTANTFF_SPRINGFF_FRICTIONFF_DAMPERFF_INERTIAFF_RAMPFF_SQUAREFF_TRIANGLEFF_SINEFF_SAW_UPFF_SAW_DOWNFF_CUSTOM"
	_InputFFCodeLowerName_0 = "ff_rumbleff_periodicff_constantff_springff_frictionff_damperff_inertiaff_rampff_squareff_triangleff_sineff_saw_upff_saw_downff_custom"
	_InputFFCodeName_1      = "FF_GAINFF_AUTOCENTER"
	_InputFFCodeLowerName_1 = "ff_gainff_autocenter"
	_InputFFCodeName_2      = "FF_MAXFF_CNT"
	_InputFFCodeLowerName_2 = "ff_maxff_cnt"
)

var (
	_InputFFCodeIndex_0 = [...]uint8{0, 9, 20, 31, 40, 51, 60, 70, 77, 86, 97, 104, 113, 124, 133}
	_InputFFCodeIndex_1 = [...]uint8{0, 7, 20}
	_InputFFCodeIndex_2 = [...]uint8{0, 6, 12}
)

func (i InputFFCode) String() string {
	switch {
	case 80 <= i && i <= 93:
		i -= 80
		return _InputFFCodeName_0[_InputFFCodeIndex_0[i]:_InputFFCodeIndex_0[i+1]]
	case 96 <= i && i <= 97:
		i -= 96
		return _InputFFCodeName_1[_InputFFCodeIndex_1[i]:_InputFFCodeIndex_1[i+1]]
	case 127 <= i && i <= 128:
		i -= 127
		return _InputFFCodeName_2[_InputFFCodeIndex_2[i]:_InputFFCodeIndex_2[i+1]]
	default:
		return fmt.Sprintf("InputFFCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _InputFFCodeNoOp() {
	var x [1]struct{}
	_ = x[FF_RUMBLE-(80)]
	_ = x[FF_PERIODIC-(81)]
	_ = x[FF_CONSTANT-(82)]
	_ = x[FF_SPRING-(83)]
	_ = x[FF_FRICTION-(84)]
	_ = x[FF_DAMPER-(85)]
	_ = x[FF_INERTIA-(86)]
	_ = x[FF_RAMP-(87)]
	_ = x[FF_SQUARE-(88)]
	_ = x[FF_TRIANGLE-(89)]
	_ = x[FF_SINE-(90)]
	_ = x[FF_SAW_UP-(91)]
	_ = x[FF_SAW_DOWN-(92)]
	_ = x[FF_CUSTOM-(93)]
	_ = x[FF_GAIN-(96)]
	_ = x[FF_AUTOCENTER-(97)]
	_ = x[FF_MAX-(127)]
	_ = x[FF_CNT-(128)]
}

var _InputFFCodeValues = []InputFFCode{FF_RUMBLE, FF_PERIODIC, FF_CONSTANT, FF_SPRING, FF_FRICTION, FF_DAMPER, FF_INERTIA, FF_RAMP, FF_SQUARE, FF_TRIANGLE, FF_SINE, FF_SAW_UP, FF_SAW_DOWN, FF_CUSTOM, FF_GAIN, FF_AUTOCENTER, FF_MAX, FF_CNT}

var _InputFFCodeNameToValueMap = map[string]InputFFCode{
	_InputFFCodeName_0[0:9]:          FF_RUMBLE,
	_InputFFCodeLowerName_0[0:9]:     FF_RUMBLE,
	_InputFFCodeName_0[9:20]:         FF_PERIODIC,
	_InputFFCodeLowerName_0[9:20]:    FF_PERIODIC,
	_InputFFCodeName_0[20:31]:        FF_CONSTANT,
	_InputFFCodeLowerName_0[20:31]:   FF_CONSTANT,
	_InputFFCodeName_0[31:40]:        FF_SPRING,
	_InputFFCodeLowerName_0[31:40]:   FF_SPRING,
	_InputFFCodeName_0[40:51]:        FF_FRICTION,
	_InputFFCodeLowerName_0[40:51]:   FF_FRICTION,
	_InputFFCodeName_0[51:60]:        FF_DAMPER,
	_InputFFCodeLowerName_0[51:60]:   FF_DAMPER,
	_InputFFCodeName_0[60:70]:        FF_INERTIA,
	_InputFFCodeLowerName_0[60:70]:   FF_INERTIA,
	_InputFFCodeName_0[70:77]:        FF_RAMP,
	_InputFFCodeLowerName_0[70:77]:   FF_RAMP,
	_InputFFCodeName_0[77:86]:        FF_SQUARE,
	_InputFFCodeLowerName_0[77:86]:   FF_SQUARE,
	_InputFFCodeName_0[86:97]:        FF_TRIANGLE,
	_InputFFCodeLowerName_0[86:97]:   FF_TRIANGLE,
	_InputFFCodeName_0[97:104]:       FF_SINE,
	_InputFFCodeLowerName_0[97:104]:  FF_SINE,
	_InputFFCodeName_0[104:113]:      FF_SAW_UP,
	_InputFFCodeLowerName_0[104:113]: FF_SAW_UP,
	_InputFFCodeName_0[113:124]:      FF_SAW_DOWN,
	_InputFFCodeLowerName_0[113:124]: FF_SAW_DOWN,
	_InputFFCodeName_0[124:133]:      FF_CUSTOM,
	_InputFFCodeLowerName_0[124:133]: FF_CUSTOM,
	_InputFFCodeName_1[0:7]:          FF_GAIN,
	_InputFFCodeLowerName_1[0:7]:     FF_GAIN,
	_InputFFCodeName_1[7:20]:         FF_AUTOCENTER,
	_InputFFCodeLowerName_1[7:20]:    FF_AUTOCENTER,
	_InputFFCodeName_2[0:6]:          FF_MAX,
	_InputFFCodeLowerName_2[0:6]:     FF_MAX,
	_InputFFCodeName_2[6:12]:         FF_CNT,
	_InputFFCodeLowerName_2[6:12]:    FF_CNT,
}

var _InputFFCodeNames = []string{
	_InputFFCodeName_0[0:9],
	_InputFFCodeName_0[9:20],
	_InputFFCodeName_0[20:31],
	_InputFFCodeName_0[31:40],
	_InputFFCodeName_0[40:51],
	_InputFFCodeName_0[51:60],
	_InputFFCodeName_0[60:70],
	_InputFFCodeName_0[70:77],
	_InputFFCodeName_0[77:86],
	_InputFFCodeName_0[86:97],
	_InputFFCodeName_0[97:104],
	_InputFFCodeName_0[104:113],
	_InputFFCodeName_0[113:124],
	_InputFFCodeName_0[124:133],
	_InputFFCodeName_1[0:7],
	_InputFFCodeName_1[7:20],
	_InputFFCodeName_2[0:6],
	_InputFFCodeName_2[6:12],
}

// InputFFCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func InputFFCodeString(s string) (InputFFCode, error) {
	if val, ok := _InputFFCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _InputFFCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to InputFFCode values", s)
}

// InputFFCodeValues returns all values of the enum
func InputFFCodeValues() []InputFFCode {
	return _InputFFCodeValues
}

// InputFFCodeStrings returns a slice of all String values of the enum
func InputFFCodeStrings() []string {
	strs := make([]string, len(_InputFFCodeNames))
	copy(strs, _InputFFCodeNames)
	return strs
}

// IsAInputFFCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i InputFFCode) IsAInputFFCode() bool {
	for _, v := range _InputFFCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
