// Code generated by "enumer -type=InputPropCode"; DO NOT EDIT.

package uapi

import (
	"fmt"
	"strings"
)

const (
	_InputPropCodeName_0      = "INPUT_PROP_POINTERINPUT_PROP_DIRECTINPUT_PROP_BUTTONPADINPUT_PROP_SEMI_MTINPUT_PROP_TOPBUTTONPADINPUT_PROP_POINTING_STICKINPUT_PROP_ACCELEROMETER"
	_InputPropCodeLowerName_0 = "input_prop_pointerinput_prop_directinput_prop_buttonpadinput_prop_semi_mtinput_prop_topbuttonpadinput_prop_pointing_stickinput_prop_accelerometer"
	_InputPropCodeName_1      = "INPUT_PROP_MAXINPUT_PROP_CNT"
	_InputPropCodeLowerName_1 = "input_prop_maxinput_prop_cnt"
)

var (
	_InputPropCodeIndex_0 = [...]uint8{0, 18, 35, 55, 73, 96, 121, 145}
	_InputPropCodeIndex_1 = [...]uint8{0, 14, 28}
)

func (i InputPropCode) String() string {
	switch {
	case 0 <= i && i <= 6:
		return _InputPropCodeName_0[_InputPropCodeIndex_0[i]:_InputPropCodeIndex_0[i+1]]
	case 31 <= i && i <= 32:
		i -= 31
		return _InputPropCodeName_1[_InputPropCodeIndex_1[i]:_InputPropCodeIndex_1[i+1]]
	default:
		return fmt.Sprintf("InputPropCode(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _InputPropCodeNoOp() {
	var x [1]struct{}
	_ = x[INPUT_PROP_POINTER-(0)]
	_ = x[INPUT_PROP_DIRECT-(1)]
	_ = x[INPUT_PROP_BUTTONPAD-(2)]
	_ = x[INPUT_PROP_SEMI_MT-(3)]
	_ = x[INPUT_PROP_TOPBUTTONPAD-(4)]
	_ = x[INPUT_PROP_POINTING_STICK-(5)]
	_ = x[INPUT_PROP_ACCELEROMETER-(6)]
	_ = x[INPUT_PROP_MAX-(31)]
	_ = x[INPUT_PROP_CNT-(32)]
}

var _InputPropCodeValues = []InputPropCode{INPUT_PROP_POINTER, INPUT_PROP_DIRECT, INPUT_PROP_BUTTONPAD, INPUT_PROP_SEMI_MT, INPUT_PROP_TOPBUTTONPAD, INPUT_PROP_POINTING_STICK, INPUT_PROP_ACCELEROMETER, INPUT_PROP_MAX, INPUT_PROP_CNT}

var _InputPropCodeNameToValueMap = map[string]InputPropCode{
	_InputPropCodeName_0[0:18]:         INPUT_PROP_POINTER,
	_InputPropCodeLowerName_0[0:18]:    INPUT_PROP_POINTER,
	_InputPropCodeName_0[18:35]:        INPUT_PROP_DIRECT,
	_InputPropCodeLowerName_0[18:35]:   INPUT_PROP_DIRECT,
	_InputPropCodeName_0[35:55]:        INPUT_PROP_BUTTONPAD,
	_InputPropCodeLowerName_0[35:55]:   INPUT_PROP_BUTTONPAD,
	_InputPropCodeName_0[55:73]:        INPUT_PROP_SEMI_MT,
	_InputPropCodeLowerName_0[55:73]:   INPUT_PROP_SEMI_MT,
	_InputPropCodeName_0[73:96]:        INPUT_PROP_TOPBUTTONPAD,
	_InputPropCodeLowerName_0[73:96]:   INPUT_PROP_TOPBUTTONPAD,
	_InputPropCodeName_0[96:121]:       INPUT_PROP_POINTING_STICK,
	_InputPropCodeLowerName_0[96:121]:  INPUT_PROP_POINTING_STICK,
	_InputPropCodeName_0[121:145]:      INPUT_PROP_ACCELEROMETER,
	_InputPropCodeLowerName_0[121:145]: INPUT_PROP_ACCELEROMETER,
	_InputPropCodeName_1[0:14]:         INPUT_PROP_MAX,
	_InputPropCodeLowerName_1[0:14]:    INPUT_PROP_MAX,
	_InputPropCodeName_1[14:28]:        INPUT_PROP_CNT,
	_InputPropCodeLowerName_1[14:28]:   INPUT_PROP_CNT,
}

var _InputPropCodeNames = []string{
	_InputPropCodeName_0[0:18],
	_InputPropCodeName_0[18:35],
	_InputPropCodeName_0[35:55],
	_InputPropCodeName_0[55:73],
	_InputPropCodeName_0[73:96],
	_InputPropCodeName_0[96:121],
	_InputPropCodeName_0[121:145],
	_InputPropCodeName_1[0:14],
	_InputPropCodeName_1[14:28],
}

// InputPropCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func InputPropCodeString(s string) (InputPropCode, error) {
	if val, ok := _InputPropCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _InputPropCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to InputPropCode values", s)
}

// InputPropCodeValues returns all values of the enum
func InputPropCodeValues() []InputPropCode {
	return _InputPropCodeValues
}

// InputPropCodeStrings returns a slice of all String values of the enum
func InputPropCodeStrings() []string {
	strs := make([]string, len(_InputPropCodeNames))
	copy(strs, _InputPropCodeNames)
	return strs
}

// IsAInputPropCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i InputPropCode) IsAInputPropCode() bool {
	for _, v := range _InputPropCodeValues {
		if i == v {
			return true
		}
	}
	return false
}
